// SPDX-License-Identifier: MIT
package welcome

import (
	"strings"
	"unicode"

	"github.com/rikvanderkemp/muxedo/internal/process"
	"github.com/rikvanderkemp/muxedo/internal/profile"
)

// Startup describes one startup command captured by the wizard.
type Startup struct {
	Command process.CommandSpec
	Mode    profile.StartupMode
}

// Panel describes one panel captured by the wizard.
type Panel struct {
	Slug       string
	WorkingDir string
	Command    process.CommandSpec
}

// WizardProfile is the in-memory profile collected by the wizard.
type WizardProfile struct {
	Title      string
	WorkingDir string
	Startup    []Startup
	Panels     []Panel
}

// shellMetaChars triggers rendering a command as a shell string rather than
// program/args. Keep this conservative; anything unfamiliar falls through to
// shell execution so we never mangle user intent.
const shellMetaChars = "|&;$`><*?()\"'\\\n\t"

// Slugify converts free-form panel names into a TOML-safe bare key. The slug
// is lowercase, uses '-' as the only separator, and collapses runs of
// non-alphanumeric characters.
func Slugify(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "panel"
	}

	var b strings.Builder
	b.Grow(len(raw))
	prevDash := true
	for _, r := range raw {
		r = unicode.ToLower(r)
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}

	slug := strings.Trim(b.String(), "-")
	if slug == "" {
		return "panel"
	}
	return slug
}

// ParseCommand turns a raw command line into a process.CommandSpec.
//
// If the line contains any shell metacharacter it is emitted as a shell
// command; otherwise it is split on whitespace into program + args. An empty
// input returns a zero spec which the caller should reject.
func ParseCommand(raw string) process.CommandSpec {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return process.CommandSpec{}
	}

	if strings.ContainsAny(trimmed, shellMetaChars) {
		return process.CommandSpec{Shell: trimmed}
	}

	tokens := strings.Fields(trimmed)
	if len(tokens) == 0 {
		return process.CommandSpec{}
	}
	spec := process.CommandSpec{Program: tokens[0]}
	if len(tokens) > 1 {
		spec.Args = append([]string(nil), tokens[1:]...)
	}
	return spec
}

// RenderTOML serialises a WizardProfile into a deterministic, human-readable
// TOML document compatible with profile.Load.
func RenderTOML(p WizardProfile) string {
	var b strings.Builder

	title := strings.TrimSpace(p.Title)
	if title == "" {
		title = profile.RandomName()
	}
	b.WriteString("# generated by muxedo first-run wizard\n")
	b.WriteString("title = ")
	writeTOMLString(&b, title)
	b.WriteByte('\n')

	workingDir := strings.TrimSpace(p.WorkingDir)
	if workingDir == "" {
		workingDir = "."
	}
	b.WriteString("workingdir = ")
	writeTOMLString(&b, workingDir)
	b.WriteByte('\n')

	for _, s := range p.Startup {
		b.WriteString("\n[[startup]]\n")
		writeCommand(&b, s.Command)
		mode := s.Mode
		if mode == "" {
			mode = profile.StartupModeAsync
		}
		b.WriteString("mode = ")
		writeTOMLString(&b, string(mode))
		b.WriteByte('\n')
	}

	for _, panel := range p.Panels {
		slug := panel.Slug
		if slug == "" {
			slug = "panel"
		}
		b.WriteString("\n[panel.")
		b.WriteString(slug)
		b.WriteString("]\n")
		if wd := strings.TrimSpace(panel.WorkingDir); wd != "" {
			b.WriteString("workingdir = ")
			writeTOMLString(&b, wd)
			b.WriteByte('\n')
		}
		writeCommand(&b, panel.Command)
	}

	return b.String()
}

func writeCommand(b *strings.Builder, cmd process.CommandSpec) {
	if cmd.Shell != "" {
		b.WriteString("shell = ")
		writeTOMLString(b, cmd.Shell)
		b.WriteByte('\n')
		return
	}
	b.WriteString("program = ")
	writeTOMLString(b, cmd.Program)
	b.WriteByte('\n')
	if len(cmd.Args) > 0 {
		b.WriteString("args = [")
		for i, a := range cmd.Args {
			if i > 0 {
				b.WriteString(", ")
			}
			writeTOMLString(b, a)
		}
		b.WriteString("]\n")
	}
}

func writeTOMLString(b *strings.Builder, s string) {
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 || r == 0x7f {
				// Fall back to Unicode escape for other control characters.
				const hex = "0123456789ABCDEF"
				b.WriteString(`\u00`)
				b.WriteByte(hex[(r>>4)&0xF])
				b.WriteByte(hex[r&0xF])
				continue
			}
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
}
